wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.7.10
      5: 0.11.2
      8:
      - 1
      - 5
bootstrap:
  desc: null
  value: true
ccp_alpha:
  desc: null
  value: 0.007953601475707478
class_weight:
  desc: null
  value: null
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 50
max_features:
  desc: null
  value: 0.8303217529492485
max_leaf_nodes:
  desc: null
  value: null
max_samples:
  desc: null
  value: 900
min_samples_leaf:
  desc: null
  value: 16
min_samples_split:
  desc: null
  value: 13
n_estimators:
  desc: null
  value: 700
