wandb_version: 1

C:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.7.10
      5: 0.11.0
      8:
      - 1
      - 5
gamma:
  desc: null
  value: scale
kernel:
  desc: null
  value: sigmoid
tol:
  desc: null
  value: 0.01
