wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.7.10
      5: 0.11.0
      8:
      - 1
      - 5
criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: 10
max_features:
  desc: null
  value: null
min_samples_split:
  desc: null
  value: 5
n_estimators:
  desc: null
  value: 100
n_jobs:
  desc: null
  value: -1
random_state:
  desc: null
  value: 42
