wandb_version: 1

criterion:
  value: entropy
max_depth:
  value: 50
max_features:
  value: null
min_samples_split:
  value: 5
n_estimators:
  value: 500
n_jobs:
  value: -1
random_state:
  value: 42
