wandb_version: 1

criterion:
  value: entropy
max_depth:
  value: null
max_features:
  value: sqrt
min_samples_split:
  value: 50
n_estimators:
  value: 100
n_jobs:
  value: -1
random_state:
  value: 42
